In [1]:
import pandas as pd
a=pd.read_csv("C:/Users/ELCOT/Downloads/Shopping_Customer_Dataset (1).csv")
a.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [6]:
print(a.tail())

     Gender Product_Category Payment_Method Membership_Level     City  \
995    Male         Clothing    Credit Card           Bronze  Houston
996  Female           Beauty    Credit Card           Silver  Houston
997    Male           Sports     Debit Card           Silver    Miami
998  Female           Beauty         PayPal             Gold  Houston
999    Male   Home & Kitchen         PayPal           Silver    Miami

     Customer_Rating  Total_Items
995              4.0            7
996              2.1            7
997              2.3            8
998              4.7            2
999              1.2            9

In [7]:
print(a.size)

7000

In [8]:
print(a.shape)

(1000, 7)

In [9]:
print(a.columns)

Index(['Gender', 'Product_Category', 'Payment_Method', 'Membership_Level',
       'City', 'Customer_Rating', 'Total_Items'],
      dtype='str')

In [17]:
a.ffill(inplace=True)
print(a.isnull().sum())

Gender              0
Product_Category    0
Payment_Method      0
Membership_Level    0
City                0
Customer_Rating     0
Total_Items         0
dtype: int64

In [28]:
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
barani=pd.read_csv("C:/Users/ELCOT/Downloads/sales_data.csv")

In [31]:
df = pd.read_csv("C:/Users/ELCOT/Downloads/weatherAUS.csv/weatherAUS.csv")

In [34]:
df["Date"]=pd.to_datetime(df["Date"], errors="coerce")

In [35]:
print(a.loc[0:4, ["Gender", "City"]])
print(a.iloc[0:5, 0:3])

   Gender         City
0    Male      Chicago
1  Female      Chicago
2  Female        Miami
3  Female     New York
4    Male  Los Angeles
   Gender Product_Category Payment_Method
0    Male           Beauty           Cash
1  Female   Home & Kitchen         PayPal
2  Female           Sports     Debit Card
3  Female      Electronics           Cash
4    Male           Sports         PayPal

In [36]:
print(a[a["Gender"] == "Female"])

     Gender Product_Category Payment_Method Membership_Level         City  \
1    Female   Home & Kitchen         PayPal           Bronze      Chicago
2    Female           Sports     Debit Card           Silver        Miami
3    Female      Electronics           Cash           Silver     New York
7    Female      Electronics           Cash           Silver      Houston
8    Female           Beauty    Credit Card           Silver     New York
..      ...              ...            ...              ...          ...
990  Female           Beauty         PayPal             Gold  Los Angeles
991  Female           Sports         PayPal           Silver        Miami
993  Female         Clothing    Credit Card           Bronze  Los Angeles
996  Female           Beauty    Credit Card           Silver      Houston
998  Female           Beauty         PayPal             Gold      Houston

     Customer_Rating  Total_Items
1                4.2            2
2                3.7            9
3                3.7            5
7                2.1            3
8                1.9           10
..               ...          ...
990              3.8           10
991              2.1            7
993              2.8            6
996              2.1            7
998              4.7            2

[499 rows x 7 columns]

In [37]:
barani=pd.read_csv("C:/Users/ELCOT/Downloads/sales_data.csv")

In [38]:
barani["Sales"]=barani["Quantity"]*barani["UnitPrice"]
barani.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
0     1031  2026-01-01  Smartphone  Electronics         3        800   2400
1     1100  2026-01-02  Headphones  Accessories         2        150    300
2     1028  2026-01-02      Laptop  Electronics         2       1200   2400
3     1089  2026-01-02      Laptop  Electronics         3       1200   3600
4     1023  2026-01-02      Tablet  Electronics         4        450   1800

In [26]:
print(a.groupby("Gender").sum(numeric_only=True))

         Customer_Rating  Total_Items
Gender
Female            1477.4         2774
Male              1414.5         2601
Unknown             74.5          160

In [39]:
import pandas as pd
import numpy as np

In [40]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [41]:
a=pd.read_csv("C:/Users/ELCOT/Downloads/Shopping_Customer_Dataset (1).csv")
a.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [42]:
le = LabelEncoder()
a["Gender_Encoded"] = le.fit_transform(a["Gender"])
print(a[["Gender", "Gender_Encoded"]])

     Gender  Gender_Encoded
0      Male               1
1    Female               0
2    Female               0
3    Female               0
4      Male               1
..      ...             ...
995    Male               1
996  Female               0
997    Male               1
998  Female               0
999    Male               1

[1000 rows x 2 columns]

In [43]:
a = pd.get_dummies(a, columns=["Payment_Method"])
print(a.head())

   Gender Product_Category Membership_Level         City  Customer_Rating  \
0    Male           Beauty          Premium      Chicago              4.6
1  Female   Home & Kitchen           Bronze      Chicago              4.2
2  Female           Sports           Silver        Miami              3.7
3  Female      Electronics           Silver     New York              3.7
4    Male           Sports           Silver  Los Angeles              4.8

   Total_Items  Gender_Encoded  Payment_Method_Cash  \
0            8               1                 True
1            2               0                False
2            9               0                False
3            5               0                 True
4           10               1                False

   Payment_Method_Credit Card  Payment_Method_Debit Card  \
0                       False                      False
1                       False                      False
2                       False                       True
3                       False                      False
4                       False                      False

   Payment_Method_PayPal
0                  False
1                   True
2                  False
3                  False
4                   True

In [54]:
print(type(a))

<class 'sklearn.preprocessing._encoders.OrdinalEncoder'>

In [55]:
import pandas as pd

a = pd.read_csv("C:/Users/ELCOT/Downloads/Shopping_Customer_Dataset (1).csv")

In [58]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["Bronze", "Silver", "Gold", "Platinum", "Premium"]])
a["Membership_Encoded"] = oe.fit_transform(a[["Membership_Level"]])
print(a[["Membership_Level", "Membership_Encoded"]])

    Membership_Level  Membership_Encoded
0            Premium                 4.0
1             Bronze                 0.0
2             Silver                 1.0
3             Silver                 1.0
4             Silver                 1.0
..               ...                 ...
995           Bronze                 0.0
996           Silver                 1.0
997           Silver                 1.0
998             Gold                 2.0
999           Silver                 1.0

[1000 rows x 2 columns]