In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/ELCOT/Downloads/crop_yield.csv")

df

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909
...,...,...,...,...,...,...,...,...,...,...
19684,Small millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [6]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [7]:
df.tail()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
19684,Small millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [8]:
df.head(10)

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909
5,Dry chillies,1997,Whole Year,Assam,13587.0,9073,2051.4,1293074.79,4211.97,0.643636
6,Gram,1997,Rabi,Assam,2979.0,1507,2051.4,283511.43,923.49,0.465455
7,Jute,1997,Kharif,Assam,94520.0,904095,2051.4,8995468.40,29301.20,9.919565
8,Linseed,1997,Rabi,Assam,10098.0,5158,2051.4,961026.66,3130.38,0.461364
9,Maize,1997,Kharif,Assam,19216.0,14721,2051.4,1828786.72,5956.96,0.615652

In [9]:
df.tail(10)

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
19679,Urad,2018,Winter,Odisha,39560.0,13123,1635.9,6416632.00,13846.00,0.352759
19680,Wheat,2018,Summer,Odisha,147.0,268,1635.9,23843.40,51.45,1.825000
19681,Jute,1998,Kharif,Nagaland,35000.0,48000,1498.0,3458000.00,10150.00,1.370000
19682,Maize,1998,Kharif,Nagaland,30000.0,37000,1498.0,2964000.00,8700.00,1.225714
19683,Rice,1998,Kharif,Nagaland,141000.0,205000,1498.0,13930800.00,40890.00,1.441429
19684,Small millets,1998,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [10]:
df.size

196890

In [11]:
df.shape

(19689, 10)

In [12]:
df.columns

Index(['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production',
       'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Yield'],
      dtype='str')

In [13]:
df.dtypes

Crop                   str
Crop_Year            int64
Season                 str
State                  str
Area               float64
Production           int64
Annual_Rainfall    float64
Fertilizer         float64
Pesticide          float64
Yield              float64
dtype: object

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Crop             19689 non-null  str
 1   Crop_Year        19689 non-null  int64
 2   Season           19689 non-null  str
 3   State            19689 non-null  str
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  int64
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
dtypes: float64(5), int64(2), str(3)
memory usage: 1.5 MB

In [15]:
df.describe()

,Crop_Year,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
count,19689.000000,1.968900e+04,1.968900e+04,19689.000000,1.968900e+04,1.968900e+04,19689.000000
mean,2009.127584,1.799266e+05,1.643594e+07,1437.755177,2.410331e+07,4.884835e+04,79.954009
std,6.498099,7.328287e+05,2.630568e+08,816.909589,9.494600e+07,2.132874e+05,878.306193
min,1997.000000,5.000000e-01,0.000000e+00,301.300000,5.417000e+01,9.000000e-02,0.000000
25%,2004.000000,1.390000e+03,1.393000e+03,940.700000,1.880146e+05,3.567000e+02,0.600000
50%,2010.000000,9.317000e+03,1.380400e+04,1247.600000,1.234957e+06,2.421900e+03,1.030000
75%,2015.000000,7.511200e+04,1.227180e+05,1643.700000,1.000385e+07,2.004170e+04,2.388889
max,2020.000000,5.080810e+07,6.326000e+09,6552.700000,4.835407e+09,1.575051e+07,21105.000000

In [16]:
df.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [18]:
num_cols = df.select_dtypes(include="number").columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [20]:
cat_cols = df.select_dtypes(include=["str", "object"]).columns

for col in cat_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print(df.isnull().sum())

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [21]:
print("Duplicates before:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

In [22]:
df["Crop_Year"] = pd.to_datetime(
    df["Crop_Year"].astype("Int64").astype(str),
    format="%Y",
    errors="coerce"
)

print(df["Crop_Year"].dtype)
df.head()

datetime64[us]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997-01-01,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997-01-01,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [23]:
df.loc[:, "Crop"]

0             Arecanut
1            Arhar/Tur
2          Castor seed
3             Coconut
4         Cotton(lint)
             ...
19684    Small millets
19685            Wheat
19686            Maize
19687             Rice
19688            Wheat
Name: Crop, Length: 19689, dtype: str

In [24]:
df.loc[:, ["Crop", "State", "Production"]]

                Crop              State  Production
0           Arecanut              Assam       56708
1          Arhar/Tur              Assam        4685
2        Castor seed              Assam          22
3           Coconut               Assam   126905000
4       Cotton(lint)              Assam         794
...              ...                ...         ...
19684  Small millets           Nagaland        2000
19685          Wheat           Nagaland        3000
19686          Maize  Jammu and Kashmir      440900
19687           Rice  Jammu and Kashmir        5488
19688          Wheat  Jammu and Kashmir      392160

[19689 rows x 3 columns]

In [25]:
df.loc[0:4, ["Crop", "Area", "Production"]]

           Crop     Area  Production
0      Arecanut  73814.0       56708
1     Arhar/Tur   6637.0        4685
2   Castor seed    796.0          22
3      Coconut   19656.0   126905000
4  Cotton(lint)   1739.0         794

In [26]:
df.iloc[0]

Crop                          Arecanut
Crop_Year          1997-01-01 00:00:00
Season                     Whole Year
State                            Assam
Area                           73814.0
Production                       56708
Annual_Rainfall                 2051.4
Fertilizer                  7024878.38
Pesticide                     22882.34
Yield                         0.796087
Name: 0, dtype: object

In [27]:
df.iloc[0:5]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997-01-01,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997-01-01,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [28]:
df.iloc[0:5, 0:3]

           Crop  Crop_Year       Season
0      Arecanut 1997-01-01  Whole Year
1     Arhar/Tur 1997-01-01  Kharif
2   Castor seed 1997-01-01  Kharif
3      Coconut  1997-01-01  Whole Year
4  Cotton(lint) 1997-01-01  Kharif

In [29]:
df.iloc[1, 2]

'Kharif     '

In [30]:
df[df["Production"] > 1000]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
5,Dry chillies,1997-01-01,Whole Year,Assam,13587.0,9073,2051.4,1293074.79,4211.97,0.643636
6,Gram,1997-01-01,Rabi,Assam,2979.0,1507,2051.4,283511.43,923.49,0.465455
...,...,...,...,...,...,...,...,...,...,...
19684,Small millets,1998-01-01,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998-01-01,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997-01-01,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997-01-01,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997-01-01,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [31]:
df[df["Area"] > 500]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997-01-01,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997-01-01,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909
...,...,...,...,...,...,...,...,...,...,...
19684,Small millets,1998-01-01,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998-01-01,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997-01-01,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997-01-01,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997-01-01,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [32]:
df[df["State"] == "Tamil Nadu"]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
1135,Arecanut,2002-01-01,Whole Year,Tamil Nadu,4956.0,0,315.9,4.691845e+05,1239.00,0.000000
1136,Arhar/Tur,2002-01-01,Kharif,Tamil Nadu,44127.0,24067,315.9,4.177503e+06,11031.75,0.535417
1137,Bajra,2002-01-01,Kharif,Tamil Nadu,102020.0,88682,315.9,9.658233e+06,25505.00,1.041667
1138,Banana,2002-01-01,Whole Year,Tamil Nadu,76771.0,2836916,315.9,7.267911e+06,19192.75,34.819643
1139,Cashewnut,2002-01-01,Whole Year,Tamil Nadu,95217.0,35885,315.9,9.014193e+06,23804.25,0.310800
...,...,...,...,...,...,...,...,...,...,...
12877,Rice,2012-01-01,Kharif,Tamil Nadu,1493276.0,4050334,706.8,2.251860e+08,462915.56,3.293226
12878,Sesamum,2012-01-01,Whole Year,Tamil Nadu,33181.0,17179,706.8,5.003695e+06,10286.11,0.477241
12879,Sugarcane,2012-01-01,Whole Year,Tamil Nadu,348379.0,34014097,706.8,5.253555e+07,107997.49,93.543548
12880,Sunflower,2012-01-01,Kharif,Tamil Nadu,10782.0,11374,706.8,1.625926e+06,3342.42,1.136400
12881,Urad,2012-01-01,Kharif,Tamil Nadu,208625.0,88706,706.8,3.146065e+07,64673.75,0.474667

In [33]:
df[
    (df["Production"] > 1000) &
    (df["Area"] > 500)
]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997-01-01,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997-01-01,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
5,Dry chillies,1997-01-01,Whole Year,Assam,13587.0,9073,2051.4,1293074.79,4211.97,0.643636
6,Gram,1997-01-01,Rabi,Assam,2979.0,1507,2051.4,283511.43,923.49,0.465455
...,...,...,...,...,...,...,...,...,...,...
19684,Small millets,1998-01-01,Kharif,Nagaland,4000.0,2000,1498.0,395200.00,1160.00,0.500000
19685,Wheat,1998-01-01,Rabi,Nagaland,1000.0,3000,1498.0,98800.00,290.00,3.000000
19686,Maize,1997-01-01,Kharif,Jammu and Kashmir,310883.0,440900,1356.2,29586735.11,96373.73,1.285000
19687,Rice,1997-01-01,Kharif,Jammu and Kashmir,275746.0,5488,1356.2,26242746.82,85481.26,0.016667
19688,Wheat,1997-01-01,Rabi,Jammu and Kashmir,239344.0,392160,1356.2,22778368.48,74196.64,1.261818

In [34]:
df[df["Yield"] > 5]

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
3,Coconut,1997-01-01,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
7,Jute,1997-01-01,Kharif,Assam,94520.0,904095,2051.4,8995468.40,29301.20,9.919565
14,Potato,1997-01-01,Whole Year,Assam,75259.0,671871,2051.4,7162399.03,23330.29,7.561304
21,Sugarcane,1997-01-01,Kharif,Assam,31318.0,1287451,2051.4,2980534.06,9708.58,41.896957
54,Sugarcane,1997-01-01,Whole Year,Karnataka,308857.0,28999269,1266.7,29393920.69,95745.67,91.747368
...,...,...,...,...,...,...,...,...,...,...
19618,Sugarcane,2016-01-01,Winter,Odisha,5493.0,344294,1460.5,841802.25,1922.55,56.160400
19636,Potato,2017-01-01,Winter,Odisha,3966.0,41812,1344.4,624407.04,1507.08,11.955455
19647,Sugarcane,2017-01-01,Winter,Odisha,3713.0,240245,1344.4,584574.72,1410.94,56.588000
19665,Potato,2018-01-01,Winter,Odisha,4900.0,54455,1635.9,794780.00,1715.00,13.017308
19676,Sugarcane,2018-01-01,Winter,Odisha,6778.0,417672,1635.9,1099391.60,2372.30,57.584545

In [35]:
df["Calculated_Yield"] = (
    df["Production"] / df["Area"].replace(0, np.nan)
)

df[["Crop", "Area", "Production", "Calculated_Yield"]].head()

           Crop     Area  Production  Calculated_Yield
0      Arecanut  73814.0       56708          0.768255
1     Arhar/Tur   6637.0        4685          0.705891
2   Castor seed    796.0          22          0.027638
3      Coconut   19656.0   126905000       6456.298331
4  Cotton(lint)   1739.0         794          0.456584

In [36]:
df.groupby("Crop")["Production"].sum()

Crop
Arecanut                     39144261
Arhar/Tur                    60913833
Bajra                       118137047
Banana                      226471979
Barley                       19498687
Black pepper                  2095650
Cardamom                       255497
Cashewnut                     3737207
Castor seed                  24049211
Coconut                  308751970278
Coriander                     3242496
Cotton(lint)                457831414
Cowpea(Lobia)                  732573
Dry chillies                 26009838
Garlic                       18798851
Ginger                       17681841
Gram                        134316823
Groundnut                   148626325
Guar seed                     7227527
Horse-gram                    5276782
Jowar                       141915435
Jute                        230423821
Khesari                       7115452
Linseed                       3187572
Maize                       410911181
Masoor                       19724553
Mesta                        14052802
Moong(Green Gram)            22490489
Moth                           913750
Niger seed                   40641053
Oilseeds total               17535438
Onion                       121700945
Other  Rabi pulses            6437766
Other Cereals                 1661859
Other Kharif pulses           5246413
Other Summer Pulses              8394
Peas & beans (Pulses)        14310509
Potato                      629688035
Ragi                         44215960
Rapeseed &Mustard            78148914
Rice                       2229301180
Safflower                     3241790
Sannhamp                       419887
Sesamum                      13542969
Small millets                13429255
Soyabean                    191659664
Sugarcane                  7236536755
Sunflower                    14644638
Sweet potato                 10409540
Tapioca                     130884693
Tobacco                      21083719
Turmeric                      9688934
Urad                         35268564
Wheat                      1810754504
other oilseeds               10033173
Name: Production, dtype: int64

In [37]:
df.groupby("State")["Production"].sum()

State
Andhra Pradesh        26076218605
Arunachal Pradesh         9522010
Assam                  3637714928
Bihar                   544953534
Chhattisgarh            143096606
Delhi                     2666022
Goa                    2193998349
Gujarat                 807581678
Haryana                 589739640
Himachal Pradesh         32297151
Jammu and Kashmir        30298377
Jharkhand                43793850
Karnataka             63772797366
Kerala               129700649853
Madhya Pradesh          834490323
Maharashtra            1878564915
Manipur                  18764635
Meghalaya                16516629
Mizoram                   2769208
Nagaland                 18748702
Odisha                  194080325
Puducherry              493815573
Punjab                  781551409
Sikkim                    2744927
Tamil Nadu            78051759253
Telangana               147700034
Tripura                  16952054
Uttar Pradesh          4442585302
Uttarakhand             179697348
West Bengal            8941179120
Name: Production, dtype: int64

In [38]:
df.groupby("Season")["Yield"].mean()

Season
Autumn           3.917482
Kharif           2.482002
Rabi             1.988518
Summer           2.997370
Whole Year     412.995463
Winter           5.287267
Name: Yield, dtype: float64

In [39]:
df.groupby("Crop")["Yield"].mean()

Crop
Arecanut                    2.073635
Arhar/Tur                   0.967348
Bajra                       2.427462
Banana                     26.851128
Barley                      1.595540
Black pepper                0.829605
Cardamom                    0.168355
Cashewnut                   3.120438
Castor seed                 0.693609
Coconut                  8652.000199
Coriander                   0.648200
Cotton(lint)                1.797044
Cowpea(Lobia)               0.813224
Dry chillies                2.078330
Garlic                      4.544886
Ginger                      6.442202
Gram                        0.876469
Groundnut                   1.360983
Guar seed                   0.951875
Horse-gram                  0.462822
Jowar                       1.072498
Jute                        7.555393
Khesari                     0.788941
Linseed                     0.473930
Maize                       3.427216
Masoor                      0.703153
Mesta                       5.389204
Moong(Green Gram)           0.530940
Moth                        0.445995
Niger seed                  0.423523
Oilseeds total              1.995559
Onion                      13.247525
Other  Rabi pulses          0.780380
Other Cereals               0.849546
Other Kharif pulses         0.699513
Other Summer Pulses         0.859925
Peas & beans (Pulses)       1.393895
Potato                     13.331718
Ragi                        1.215408
Rapeseed &Mustard           0.791568
Rice                        2.218495
Safflower                   0.565482
Sannhamp                    1.274959
Sesamum                     0.611750
Small millets               0.768722
Soyabean                    1.083194
Sugarcane                  51.727439
Sunflower                   0.934086
Sweet potato                9.240788
Tapioca                    16.667301
Tobacco                     2.110708
Turmeric                    3.325392
Urad                        0.584048
Wheat                       2.005086
other oilseeds              1.789220
Name: Yield, dtype: float64

In [40]:
df.groupby("Crop").agg({
    "Area": "sum",
    "Production": "sum",
    "Yield": "mean"
})

                               Area    Production        Yield
Crop
Arecanut               8.775333e+06      39144261     2.073635
Arhar/Tur              8.235357e+07      60913833     0.967348
Bajra                  9.335810e+07     118137047     2.427462
Banana                 7.127527e+06     226471979    26.851128
Barley                 9.270084e+06      19498687     1.595540
Black pepper           4.362226e+06       2095650     0.829605
Cardamom               1.308206e+06        255497     0.168355
Cashewnut              7.558678e+06       3737207     3.120438
Castor seed            1.659632e+07      24049211     0.693609
Coconut                3.845346e+07  308751970278  8652.000199
Coriander              4.520834e+06       3242496     0.648200
Cotton(lint)           2.210101e+08     457831414     1.797044
Cowpea(Lobia)          1.309876e+06        732573     0.813224
Dry chillies           1.258819e+07      26009838     2.078330
Garlic                 2.893172e+06      18798851     4.544886
Ginger                 1.811810e+06      17681841     6.442202
Gram                   1.454909e+08     134316823     0.876469
Groundnut              1.236583e+08     148626325     1.360983
Guar seed              6.114924e+06       7227527     0.951875
Horse-gram             1.218425e+07       5276782     0.462822
Jowar                  1.645358e+08     141915435     1.072498
Jute                   1.814415e+07     230423821     7.555393
Khesari                9.973860e+06       7115452     0.788941
Linseed                7.764955e+06       3187572     0.473930
Maize                  1.578883e+08     410911181     3.427216
Masoor                 2.631433e+07      19724553     0.703153
Mesta                  1.854131e+06      14052802     5.389204
Moong(Green Gram)      5.193911e+07      22490489     0.530940
Moth                   1.814438e+06        913750     0.445995
Niger seed             5.726699e+07      40641053     0.423523
Oilseeds total         8.571090e+06      17535438     1.995559
Onion                  8.867131e+06     121700945    13.247525
Other  Rabi pulses     1.115316e+07       6437766     0.780380
Other Cereals          1.891235e+06       1661859     0.849546
Other Kharif pulses    1.208778e+07       5246413     0.699513
Other Summer Pulses    1.912000e+04          8394     0.859925
Peas & beans (Pulses)  1.285124e+07      14310509     1.393895
Potato                 3.140623e+07     629688035    13.331718
Ragi                   3.087742e+07      44215960     1.215408
Rapeseed &Mustard      7.206145e+07      78148914     0.791568
Rice                   9.918581e+08    2229301180     2.218495
Safflower              5.725914e+06       3241790     0.565482
Sannhamp               2.904270e+05        419887     1.274959
Sesamum                3.090880e+07      13542969     0.611750
Small millets          2.164863e+07      13429255     0.768722
Soyabean               1.860803e+08     191659664     1.083194
Sugarcane              1.027778e+08    7236536755    51.727439
Sunflower              2.613820e+07      14644638     0.934086
Sweet potato           1.190929e+06      10409540     9.240788
Tapioca                4.344481e+06     130884693    16.667301
Tobacco                9.602803e+06      21083719     2.110708
Turmeric               2.722733e+06       9688934     3.325392
Urad                   6.810398e+07      35268564     0.584048
Wheat                  6.022748e+08    1810754504     2.005086
other oilseeds         8.786430e+05      10033173     1.789220

In [41]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Crop_Encoded"] = le.fit_transform(df["Crop"])

df[["Crop", "Crop_Encoded"]].head()

           Crop  Crop_Encoded
0      Arecanut             0
1     Arhar/Tur             1
2   Castor seed             8
3      Coconut              9
4  Cotton(lint)            11

In [42]:
df_onehot = pd.get_dummies(
    df,
    columns=["Season"],
    dtype=int
)

df_onehot.head()

,Crop,Crop_Year,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Calculated_Yield,Crop_Encoded,Season_Autumn,Season_Kharif,Season_Rabi,Season_Summer,Season_Whole Year,Season_Winter
0,Arecanut,1997-01-01,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087,0.768255,0,0,0,0,0,1,0
1,Arhar/Tur,1997-01-01,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435,0.705891,1,0,1,0,0,0,0
2,Castor seed,1997-01-01,Assam,796.0,22,2051.4,75755.32,246.76,0.238333,0.027638,8,0,1,0,0,0,0
3,Coconut,1997-01-01,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331,9,0,0,0,0,1,0
4,Cotton(lint),1997-01-01,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909,0.456584,11,0,1,0,0,0,0

In [43]:
df_onehot.columns

Index(['Crop', 'Crop_Year', 'State', 'Area', 'Production', 'Annual_Rainfall',
       'Fertilizer', 'Pesticide', 'Yield', 'Calculated_Yield', 'Crop_Encoded',
       'Season_Autumn     ', 'Season_Kharif     ', 'Season_Rabi       ',
       'Season_Summer     ', 'Season_Whole Year ', 'Season_Winter     '],
      dtype='str')

In [44]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

df["Season_Ordinal"] = oe.fit_transform(
    df[["Season"]]
)

df[["Season", "Season_Ordinal"]].head()

        Season  Season_Ordinal
0  Whole Year              4.0
1  Kharif                  1.0
2  Kharif                  1.0
3  Whole Year              4.0
4  Kharif                  1.0

In [45]:
num_df = df.select_dtypes(include="number")

In [46]:
num_df.mean()

Area                1.799266e+05
Production          1.643594e+07
Annual_Rainfall     1.437755e+03
Fertilizer          2.410331e+07
Pesticide           4.884835e+04
Yield               7.995401e+01
Calculated_Yield    8.384078e+01
Crop_Encoded        2.935766e+01
Season_Ordinal      2.037381e+00
dtype: float64

In [47]:
num_df.median()

Area                9.317000e+03
Production          1.380400e+04
Annual_Rainfall     1.247600e+03
Fertilizer          1.234957e+06
Pesticide           2.421900e+03
Yield               1.030000e+00
Calculated_Yield    1.035673e+00
Crop_Encoded        3.100000e+01
Season_Ordinal      2.000000e+00
dtype: float64

In [48]:
num_df.mode().iloc[0]

Area                   1.0000
Production             0.0000
Annual_Rainfall     1434.5875
Fertilizer           150.8000
Pesticide              0.9900
Yield                  1.0000
Calculated_Yield       1.0000
Crop_Encoded          40.0000
Season_Ordinal         1.0000
Name: 0, dtype: float64

In [49]:
num_df.std()

Area                7.328287e+05
Production          2.630568e+08
Annual_Rainfall     8.169096e+02
Fertilizer          9.494600e+07
Pesticide           2.132874e+05
Yield               8.783062e+02
Calculated_Yield    9.235971e+02
Crop_Encoded        1.556086e+01
Season_Ordinal      1.222513e+00
dtype: float64

In [50]:
num_df.var()

Area                5.370379e+11
Production          6.919890e+16
Annual_Rainfall     6.673413e+05
Fertilizer          9.014744e+15
Pesticide           4.549150e+10
Yield               7.714218e+05
Calculated_Yield    8.530316e+05
Crop_Encoded        2.421403e+02
Season_Ordinal      1.494539e+00
dtype: float64

In [51]:
num_df.min()

Area                  0.50
Production            0.00
Annual_Rainfall     301.30
Fertilizer           54.17
Pesticide             0.09
Yield                 0.00
Calculated_Yield      0.00
Crop_Encoded          0.00
Season_Ordinal        0.00
dtype: float64

In [52]:
num_df.max()

Area                5.080810e+07
Production          6.326000e+09
Annual_Rainfall     6.552700e+03
Fertilizer          4.835407e+09
Pesticide           1.575051e+07
Yield               2.110500e+04
Calculated_Yield    2.110500e+04
Crop_Encoded        5.400000e+01
Season_Ordinal      5.000000e+00
dtype: float64

In [53]:
num_df.max() - num_df.min()

Area                5.080810e+07
Production          6.326000e+09
Annual_Rainfall     6.251400e+03
Fertilizer          4.835407e+09
Pesticide           1.575051e+07
Yield               2.110500e+04
Calculated_Yield    2.110500e+04
Crop_Encoded        5.400000e+01
Season_Ordinal      5.000000e+00
dtype: float64

In [54]:
Q1 = num_df.quantile(0.25)

Q1

Area                  1390.00000
Production            1393.00000
Annual_Rainfall        940.70000
Fertilizer          188014.62000
Pesticide              356.70000
Yield                    0.60000
Calculated_Yield         0.59585
Crop_Encoded            17.00000
Season_Ordinal           1.00000
Name: 0.25, dtype: float64

In [55]:
Q2 = num_df.quantile(0.50)

Q2

Area                9.317000e+03
Production          1.380400e+04
Annual_Rainfall     1.247600e+03
Fertilizer          1.234957e+06
Pesticide           2.421900e+03
Yield               1.030000e+00
Calculated_Yield    1.035673e+00
Crop_Encoded        3.100000e+01
Season_Ordinal      2.000000e+00
Name: 0.5, dtype: float64

In [56]:
Q3 = num_df.quantile(0.75)

Q3

Area                7.511200e+04
Production          1.227180e+05
Annual_Rainfall     1.643700e+03
Fertilizer          1.000385e+07
Pesticide           2.004170e+04
Yield               2.388889e+00
Calculated_Yield    2.463386e+00
Crop_Encoded        4.300000e+01
Season_Ordinal      3.000000e+00
Name: 0.75, dtype: float64

In [57]:
IQR = Q3 - Q1

IQR

Area                7.372200e+04
Production          1.213250e+05
Annual_Rainfall     7.030000e+02
Fertilizer          9.815833e+06
Pesticide           1.968500e+04
Yield               1.788889e+00
Calculated_Yield    1.867536e+00
Crop_Encoded        2.600000e+01
Season_Ordinal      2.000000e+00
dtype: float64

In [58]:
num_df.skew()

Area                21.858218
Production          19.299193
Annual_Rainfall      2.131785
Fertilizer          13.412599
Pesticide           25.635746
Yield               12.785265
Calculated_Yield    12.807936
Crop_Encoded        -0.221717
Season_Ordinal       0.739242
dtype: float64

In [59]:
num_df.kurt()

Area                1202.624968
Production           388.567239
Annual_Rainfall        6.974983
Fertilizer           408.454102
Pesticide           1546.727623
Yield                175.577323
Calculated_Yield     175.791312
Crop_Encoded          -1.117669
Season_Ordinal        -0.661892
dtype: float64

In [60]:
Q1 = num_df.quantile(0.25)
Q3 = num_df.quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outlier_mask = (
    (num_df < lower_limit) |
    (num_df > upper_limit)
)

outliers = num_df[outlier_mask.any(axis=1)]

print("Number of outlier rows:", len(outliers))

outliers.head()

Number of outlier rows: 7386

,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Calculated_Yield,Crop_Encoded,Season_Ordinal
3,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739,6456.298331,9,4.0
7,94520.0,904095,2051.4,8995468.40,29301.20,9.919565,9.565118,21,1.0
14,75259.0,671871,2051.4,7162399.03,23330.29,7.561304,8.927451,37,4.0
15,279292.0,154772,2051.4,26580219.64,86580.52,0.554783,0.554158,39,2.0
16,607358.0,398311,2051.4,57802260.86,188280.98,0.780870,0.655809,40,0.0

In [61]:
cv = (num_df.std() / num_df.mean()) * 100

print(cv)

Area                 407.293194
Production          1600.497565
Annual_Rainfall       56.818407
Fertilizer           393.912682
Pesticide            436.631616
Yield               1098.514261
Calculated_Yield    1101.608381
Crop_Encoded          53.004414
Season_Ordinal        60.004157
dtype: float64