In [2]:
pip install loc

Requirement already satisfied: loc in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.0.2)
Requirement already satisfied: bidict in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from loc) (0.24.1)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
ab=pd.read_csv("C:/Users/ELCOT/Downloads/sales_data.csv")

In [9]:
ab.loc[0:19]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
16     1027  2026-01-06      Tablet  Electronics         2        450
17     1061  2026-01-07  Headphones  Accessories         3        150
18     1058  2026-01-07      Laptop  Electronics         2       1200
19     1077  2026-01-07  Headphones  Accessories         2        150

In [10]:
ab.iloc[0:10, 0:5]

   OrderID        Date     Product     Category  Quantity
0     1031  2026-01-01  Smartphone  Electronics         3
1     1100  2026-01-02  Headphones  Accessories         2
2     1028  2026-01-02      Laptop  Electronics         2
3     1089  2026-01-02      Laptop  Electronics         3
4     1023  2026-01-02      Tablet  Electronics         4
5     1072  2026-01-02  Smartphone  Electronics         4
6     1055  2026-01-03  Headphones  Accessories         1
7     1020  2026-01-03      Laptop  Electronics         1
8     1082  2026-01-03  Smartphone  Electronics         4
9     1085  2026-01-04      Laptop  Electronics         1

In [11]:
ab[ab["Quantity"] > 4]

Empty DataFrame
Columns: [OrderID, Date, Product, Category, Quantity, UnitPrice]
Index: []

In [12]:
ab[ab["Quantity"] < 4]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
6      1055  2026-01-03  Headphones  Accessories         1        150
..      ...         ...         ...          ...       ...        ...
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
99     1047  2026-01-30      Tablet  Electronics         3        450

[69 rows x 6 columns]

In [13]:
ab[ab["Quantity"] >= 4]

    OrderID        Date     Product     Category  Quantity  UnitPrice
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
24     1087  2026-01-08      Laptop  Electronics         4       1200
25     1006  2026-01-08  Smartwatch  Accessories         4        250
27     1069  2026-01-09      Tablet  Electronics         4        450
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
40     1066  2026-01-14  Headphones  Accessories         4        150
41     1081  2026-01-15      Tablet  Electronics         4        450
45     1075  2026-01-15  Smartwatch  Accessories         4        250
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
49     1062  2026-01-18  Smartwatch  Accessories         4        250
58     1073  2026-01-20  Smartwatch  Accessories         4        250
71     1015  2026-01-24      Laptop  Electronics         4       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
88     1042  2026-01-28      Tablet  Electronics         4        450
94     1007  2026-01-29  Smartphone  Electronics         4        800
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250

In [14]:
ab[ab["Quantity"] <= 4]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [15]:
ab[(ab["Quantity"] > 2) & (ab["UnitPrice"] > 100)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
22     1080  2026-01-08  Headphones  Accessories         3        150
24     1087  2026-01-08      Laptop  Electronics         4       1200
25     1006  2026-01-08  Smartwatch  Accessories         4        250
26     1060  2026-01-09  Smartwatch  Accessories         3        250
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
33     1036  2026-01-12  Headphones  Accessories         3        150
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
45     1075  2026-01-15  Smartwatch  Accessories         4        250
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
49     1062  2026-01-18  Smartwatch  Accessories         4        250
52     1067  2026-01-18  Smartwatch  Accessories         3        250
55     1050  2026-01-19  Smartphone  Electronics         3        800
57     1002  2026-01-20  Headphones  Accessories         3        150
58     1073  2026-01-20  Smartwatch  Accessories         4        250
62     1071  2026-01-21  Smartphone  Electronics         3        800
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
80     1098  2026-01-26      Tablet  Electronics         3        450
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
86     1076  2026-01-28  Headphones  Accessories         3        150
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
94     1007  2026-01-29  Smartphone  Electronics         4        800
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [16]:
ab[(ab["Quantity"] > 4) | (ab["Product"] == "Smartphone")]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
35     1032  2026-01-12  Smartphone  Electronics         1        800
37     1099  2026-01-12  Smartphone  Electronics         3        800
55     1050  2026-01-19  Smartphone  Electronics         3        800
56     1053  2026-01-20  Smartphone  Electronics         2        800
62     1071  2026-01-21  Smartphone  Electronics         3        800
74     1054  2026-01-25  Smartphone  Electronics         4        800
75     1037  2026-01-25  Smartphone  Electronics         2        800
94     1007  2026-01-29  Smartphone  Electronics         4        800

In [17]:
ab[~(ab["Quantity"] == 4)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
6      1055  2026-01-03  Headphones  Accessories         1        150
..      ...         ...         ...          ...       ...        ...
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
99     1047  2026-01-30      Tablet  Electronics         3        450

[69 rows x 6 columns]

In [18]:
ab.sort_values("Quantity", ascending=True)

    OrderID        Date     Product     Category  Quantity  UnitPrice
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
61     1008  2026-01-21  Smartwatch  Accessories         1        250
50     1086  2026-01-18      Laptop  Electronics         1       1200
..      ...         ...         ...          ...       ...        ...
74     1054  2026-01-25  Smartphone  Electronics         4        800
94     1007  2026-01-29  Smartphone  Electronics         4        800
88     1042  2026-01-28      Tablet  Electronics         4        450
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250

[100 rows x 6 columns]

In [19]:
ab.sort_values("Quantity", ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
4      1023  2026-01-02      Tablet  Electronics         4        450
24     1087  2026-01-08      Laptop  Electronics         4       1200
..      ...         ...         ...          ...       ...        ...
76     1064  2026-01-25      Tablet  Electronics         1        450
85     1065  2026-01-28  Smartwatch  Accessories         1        250
95     1026  2026-01-30      Tablet  Electronics         1        450
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200

[100 rows x 6 columns]

In [20]:
ab.sort_values(["Category", "Quantity"], ascending=[True, False])

    OrderID        Date     Product     Category  Quantity  UnitPrice
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
25     1006  2026-01-08  Smartwatch  Accessories         4        250
30     1014  2026-01-11  Smartwatch  Accessories         4        250
..      ...         ...         ...          ...       ...        ...
72     1024  2026-01-24      Tablet  Electronics         1        450
76     1064  2026-01-25      Tablet  Electronics         1        450
81     1010  2026-01-26      Laptop  Electronics         1       1200
93     1035  2026-01-29      Laptop  Electronics         1       1200
95     1026  2026-01-30      Tablet  Electronics         1        450

[100 rows x 6 columns]

In [22]:
ab["Total"] = ab["Quantity"] * ab["UnitPrice"]
ab.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  Total
0     1031  2026-01-01  Smartphone  Electronics         3        800   2400
1     1100  2026-01-02  Headphones  Accessories         2        150    300
2     1028  2026-01-02      Laptop  Electronics         2       1200   2400
3     1089  2026-01-02      Laptop  Electronics         3       1200   3600
4     1023  2026-01-02      Tablet  Electronics         4        450   1800

In [23]:
ab["NewColumn"] = ab["Quantity"] + ab["UnitPrice"]
ab.head()

,OrderID,Date,Product,Category,Quantity,UnitPrice,Total,NewColumn
0,1031,2026-01-01,Smartphone,Electronics,3,800,2400,803
1,1100,2026-01-02,Headphones,Accessories,2,150,300,152
2,1028,2026-01-02,Laptop,Electronics,2,1200,2400,1202
3,1089,2026-01-02,Laptop,Electronics,3,1200,3600,1203
4,1023,2026-01-02,Tablet,Electronics,4,450,1800,454

In [24]:
ab.groupby("Category")["Quantity"].min()

Category
Accessories    1
Electronics    1
Name: Quantity, dtype: int64

In [25]:
ab.groupby("Category")["Quantity"].max()

Category
Accessories    4
Electronics    4
Name: Quantity, dtype: int64

In [26]:
ab.groupby("Category")["Quantity"].sum()

Category
Accessories    111
Electronics    155
Name: Quantity, dtype: int64

In [27]:
ab.groupby("Category")["Quantity"].mean()

Category
Accessories    2.642857
Electronics    2.672414
Name: Quantity, dtype: float64

In [28]:
ab.groupby("Category")["Quantity"].count()

Category
Accessories    42
Electronics    58
Name: Quantity, dtype: int64

In [29]:
ab.groupby("Category")["Quantity"].std()

Category
Accessories    1.122311
Electronics    1.160580
Name: Quantity, dtype: float64